### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by highwang** [zhangxinsong-nlp/XFM#6]
Hi, I am a beginner and am very interested in your project. I want to know where did the file answer_list.json used in VQA.yaml come from? I couldn't find it in the VQA dataset

**Comment by zhangxinsong-nlp** [comment]
Hi, you can find JSON files for downstream tasks here. https://drive.google.com/file/d/1XFz1Vtz7MCBLn4_1QEojhFJ5Iw3eH3X4/view

**Comment by bowen-upenn** [comment]
We are researchers who are interested in your work and the Visual Question Answering tasks.

Your paper mentioned the performance on VQA v2 test-dev and test-std datasets. However, the ground-truth answers to them are not available on the official website https://visualqa.org/download.html or in your finetune.zip. 

Can you please explain how you evaluated your performance on these datasets? Did you submit your answers to the VQA Challenge 2021 to obtain your scores, instead of evaluating them locally? Thank you!
